contents.md, spec/03_number_spec.rb, spec/04_hash_spec.rb, spec/06_equality_spec.rb, spec/14_find_number_spec.rb, spec_answers/02_array_answer.rb, spec_answers/04_hash_answer.rb, spec_answers/06_equality_answer.rb, spec_answers/14_find_number_answer.rb
Looked at examples of the typos that Andrew found and checked the current files to remove similar typos.
=> fixed minor typos

spec/reusing_custom_matchers.rb
Added reusing_custom_matchers.rb lesson
=> Custom matchers

spec/13_input_output_spec.rb, spec_answers/13_input_output_answer.rb
=> replace satisfy with custom matcher

contents.md, lib/13_input_output.rb, spec/13_input_output_spec.rb, spec_answers/13_input_output_answer.rb
Update tests to use stubs to clearly test for verify_input and player_input
=> Input output

spec/04_hash_spec.rb
=> Fixes typo

spec/04_hash_spec.rb
=> Fixed car make's name

spec/06_equality_spec.rb
Matching the example description to the expectation.
=> Change 'eq' to 'eql'

spec/03_number_spec.rb
I believe you meant 'explicitly'
=> Correct 'implicitly'

contents.md, spec/13_input_output_spec.rb, spec/14_find_number_spec.rb, spec_answers/13_input_output_answer.rb, spec_answers/14_find_number_answer.rb
In reviewing file 13, I changed the documentation link to be the one that @aaron-contreras suggested, because it clearly talked about method stubs returning a value. In addition, I move the 'Testing For Beginners' link to this file, because it gives an extended explantation on stubs.
In reviewing file 14, I updated the explanation at the top regarding using doubles in TDD. I liked the explanation of examples in the 'RSpec mocks and stubs in plain English' article that @aaron-contreras suggested, so I added it as an additional resource.
In addition, in file 14, I expanded on the typical Red-Green-Refactor workflow. Since, the assignment already breaks down the workflow for each of the 3 methods to be write a test, write the method, then write the rest of the tests. Explicitly writing out …
=> update TDD and doubles explanation

lib/13_input_output.rb, spec/13_input_output_spec.rb, spec_answers/13_input_output_answer.rb
These suggestions are from private discussions with @msespos.
=> Input clarifications

spec/14_find_number_spec.rb, spec/15_binary_search_spec.rb
I made notes of small things I noticed while working thru the exercises and changed a few things, nothing major, all in spec files 13 thru 15.
=> A few typo fixes, etc.

spec/15_binary_game_spec.rb, spec_answers/15_binary_game_answer.rb
Adds a resource clarifying `.with(arguments)`
=> add match argument resource

spec/15_binary_search_spec.rb
=> add file explanation

spec/15_binary_game_spec.rb, spec/15_binary_search_spec.rb, spec_answers/15_binary_game_answer.rb
I did add a hint in for Assignment 3. See what you think! Also I made the Sandi Metz video a requirement. See how that reads. Hope these changes help!
=> Copyedit files for Lesson 15

spec/13_input_output_spec.rb, spec_answers/13_input_output_answer.rb
Instead of teaching about mocks and providing a link that barely talks about them. I find that using the terminology 'message expectation' is much more descriptive of what is happening.
=> add message expectation

spec/13_input_output_spec.rb, spec_answers/13_input_output_answer.rb
The only files that did not have assignment numbers (after they start being scattered throughout the file) is 13_input_output. 
Closes issue #57
=> add numbers to assignments

lib/13_input_output.rb, lib/16_caesar_breaker.rb, lib/16_caesar_translator.rb, spec/09_custom_matcher.rb, spec/13_input_output_spec.rb, spec/16_caesar_breaker_spec.rb, spec/16_caesar_translator_spec.rb, spec_answers/09_custom_matcher_answer.rb, spec_answers/13_input_output_answer.rb, spec_answers/16_caesar_answer.rb
I didn't touch "scenario" for now as I think that is a separate issue that needs to be dealt with across all of the files.
=> Edits to Lesson 16

lib/13_input_output.rb, lib/15a_binary_game.rb, lib/16a_caesar_breaker.rb, spec/03_number_spec.rb, spec/13_input_output_spec.rb, spec/15a_binary_game_spec.rb, spec/15b_binary_search_spec.rb, spec/16a_caesar_breaker_spec.rb, spec/16b_caesar_translator_spec.rb, spec_answers/13_input_output_answer.rb, spec_answers/15a_binary_game_answer.rb, spec_answers/16a_caesar_answer.rb
spec/15b and spec/16b had changes from (#73) in the spec files, but not in the related spec_answer files. I therefore did not touch spec_answers/15b or spec_answers/16b
This branch was apparently 15 commits behind the master, but was able to merge. See if for some reason it's causing unwanted changes.
=> Various edits to lib, spec, and spec_answers files

spec/16a_caesar_breaker_spec.rb, spec_answers/16a_caesar_answer.rb
=> add error explanation

spec/05_truthy_falsy_spec.rb, spec/14_find_number_spec.rb, spec/15a_binary_game_spec.rb, spec/16a_caesar_breaker_spec.rb, spec_answers/12_magic_seven_answer.rb, spec_answers/13_input_output_answer.rb, spec_answers/14_find_number_answer.rb, spec_answers/15a_binary_game_answer.rb, spec_answers/16a_caesar_answer.rb
Looked at the consistent use of lesson, example, assignment & exercise. 
I updated the word 'scenario' with 'conditions', because it has a similar semantic meaning to the previous use of 'scenario'. Plus, the meaning in the "testing world" fits better:
https://www.geeksforgeeks.org/difference-between-test-scenario-and-test-condition-in-software-engineering/
In addition, I noticed several times that the answer file did not have the same wording as the spec file. So, I went through all of the file & made sure that the wording was the same in both files.
=> 79 consistent wording

contents.md, lib/12_magic_seven.rb, lib/13_input_output.rb, lib/14_find_number.rb, lib/16a_caesar_breaker.rb, spec/03_number_spec.rb, spec/10_drink_spec.rb, spec/12_magic_seven_spec.rb, spec/13_input_output_spec.rb, spec/14_find_number_spec.rb, spec/16a_caesar_breaker_spec.rb, spec_answers/10_drink_answer.rb, spec_answers/12_magic_seven_answer.rb, spec_answers/13_input_output_answer.rb, spec_answers/14_find_number_answer.rb, spec_answers/16a_caesar_answer.rb
Upon learning that instance_variable_set is a code smell, these changes remove the need from using it in entire playground.
=> Remove instance_variable_set

lib/16_caesar_main.rb, lib/16a_caesar_breaker.rb, lib/16b_caesar_translator.rb, lib/16c_database.rb, spec/16a_caesar_breaker_spec.rb, spec/16b_caesar_translator_spec.rb, spec_answers/16a_caesar_answer.rb
Added a main file, like I did in lesson 15, so that these files can be run without having to uncomment the commands. Also, updated the explanations based on the changes to lesson 15.
=> add Caesar main file & update tests
